"use client";
// ═════════════════════════════════════════════════════════════════════════
// Report export.
//
// GET /api/report/{job_id} returns a Markdown report the backend generated
// during synthesis. Two affordances: download the file as the server sends
// it, or preview the exact text in a sheet before committing to it. If the
// report has not been written the 404 is surfaced verbatim rather than
// silently offering a broken download.
// ═════════════════════════════════════════════════════════════════════════
import { useCallback, useState } from "react";
import { describeError, fetchReportText, reportUrl } from "@/lib/api";
import CopyButton from "./primitives/CopyButton";
import Icon from "./primitives/Icon";
import Sheet from "./primitives/Sheet";

type LoadState = "idle" | "loading" | "ready" | "error";

export interface ReportButtonProps {
  jobId: string;
  /** Disabled with a stated reason when the job did not complete. */
  disabledReason: string | null;
}

export default function ReportButton({ jobId, disabledReason }: ReportButtonProps) {
  const [state, setState] = useState<LoadState>("idle");
  const [text, setText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(false);

  const preview = useCallback(async () => {
    setOpen(true);
    if (state === "ready") return;
    setState("loading");
    setError(null);
    try {
      const body = await fetchReportText(jobId);
      setText(body);
      setState("ready");
    } catch (err) {
      const apiErr = describeError(err);
      setError(apiErr.hint ? `${apiErr.message} — ${apiErr.hint}` : apiErr.message);
      setState("error");
    }
  }, [jobId, state]);

  const blocked = disabledReason !== null;

  return (
    <>
      <div className="flex items-center gap-1.5">
        <a
          className={`sq-btn sq-btn-sm ${blocked ? "pointer-events-none opacity-45" : ""}`}
          href={blocked ? undefined : reportUrl(jobId)}
          download={`satquery-report-${jobId}.md`}
          aria-disabled={blocked || undefined}
          title={disabledReason ?? "Download the Markdown report generated by the pipeline"}
        >
          <Icon name="download" size={12} />
          Report
        </a>
        <button
          type="button"
          className="sq-icon-btn"
          onClick={preview}
          disabled={blocked}
          aria-label="Preview report"
          title={disabledReason ?? "Preview the report text"}
        >
          <Icon name="eye" size={13} />
        </button>
      </div>

      <Sheet open={open} onClose={() => setOpen(false)} title={`Report · ${jobId}`}>
        {state === "loading" && (
          <p className="text-[12px] text-[var(--color-ink-3)]">Fetching report…</p>
        )}
        {state === "error" && (
          <div className="flex gap-2 text-[12px] leading-snug text-[var(--color-fault)]">
            <Icon name="fault" size={14} className="mt-[1px] shrink-0" />
            <span>{error}</span>
          </div>
        )}
        {state === "ready" && text !== null && (
          <>
            <div className="mb-2 flex items-center gap-2">
              <CopyButton text={text} label="Copy Markdown" />
              <a className="sq-btn sq-btn-sm" href={reportUrl(jobId)} download={`satquery-report-${jobId}.md`}>
                <Icon name="download" size={12} />
                Download
              </a>
              <span className="sq-num ml-auto text-[10px] text-[var(--color-ink-4)]">
                {text.length.toLocaleString("en-US")} chars
              </span>
            </div>
            <pre className="sq-mono sq-scroll max-h-[68vh] overflow-auto whitespace-pre-wrap break-words rounded border border-[var(--hair)] bg-[var(--color-panel)] p-3 text-[11px] leading-[1.65] text-[var(--color-ink-2)]">
              {text}
            </pre>
          </>
        )}
      </Sheet>
    </>
  );
}
